% Options for packages loaded elsewhere
\PassOptionsToPackage{unicode}{hyperref}
\PassOptionsToPackage{hyphens}{url}
%
\documentclass[
]{article}
\usepackage{amsmath,amssymb}
\usepackage{iftex}
\ifPDFTeX
  \usepackage[T1]{fontenc}
  \usepackage[utf8]{inputenc}
  \usepackage{textcomp} % provide euro and other symbols
\else % if luatex or xetex
  \usepackage{unicode-math} % this also loads fontspec
  \defaultfontfeatures{Scale=MatchLowercase}
  \defaultfontfeatures[\rmfamily]{Ligatures=TeX,Scale=1}
\fi
\usepackage{lmodern}
\ifPDFTeX\else
  % xetex/luatex font selection
\fi
% Use upquote if available, for straight quotes in verbatim environments
\IfFileExists{upquote.sty}{\usepackage{upquote}}{}
\IfFileExists{microtype.sty}{% use microtype if available
  \usepackage[]{microtype}
  \UseMicrotypeSet[protrusion]{basicmath} % disable protrusion for tt fonts
}{}
\makeatletter
\@ifundefined{KOMAClassName}{% if non-KOMA class
  \IfFileExists{parskip.sty}{%
    \usepackage{parskip}
  }{% else
    \setlength{\parindent}{0pt}
    \setlength{\parskip}{6pt plus 2pt minus 1pt}}
}{% if KOMA class
  \KOMAoptions{parskip=half}}
\makeatother
\usepackage{xcolor}
\usepackage[margin=1in]{geometry}
\usepackage{graphicx}
\makeatletter
\newsavebox\pandoc@box
\newcommand*\pandocbounded[1]{% scales image to fit in text height/width
  \sbox\pandoc@box{#1}%
  \Gscale@div\@tempa{\textheight}{\dimexpr\ht\pandoc@box+\dp\pandoc@box\relax}%
  \Gscale@div\@tempb{\linewidth}{\wd\pandoc@box}%
  \ifdim\@tempb\p@<\@tempa\p@\let\@tempa\@tempb\fi% select the smaller of both
  \ifdim\@tempa\p@<\p@\scalebox{\@tempa}{\usebox\pandoc@box}%
  \else\usebox{\pandoc@box}%
  \fi%
}
% Set default figure placement to htbp
\def\fps@figure{htbp}
\makeatother
\setlength{\emergencystretch}{3em} % prevent overfull lines
\providecommand{\tightlist}{%
  \setlength{\itemsep}{0pt}\setlength{\parskip}{0pt}}
\setcounter{secnumdepth}{5}
\usepackage{booktabs}
\usepackage{longtable}
\usepackage{array}
\usepackage[stretch=10]{microtype}
\usepackage{bookmark}
\IfFileExists{xurl.sty}{\usepackage{xurl}}{} % add URL line breaks if available
\urlstyle{same}
\hypersetup{
  pdftitle={Conventional MAIHDA --- ACIC 2022 Track 1a (Readable Strata)},
  pdfauthor={Yiyang Gao},
  hidelinks,
  pdfcreator={LaTeX via pandoc}}

\title{Conventional MAIHDA --- ACIC 2022 Track 1a (Readable Strata)}
\author{Yiyang Gao}
\date{2025-10-07}

\begin{document}
\maketitle

{
\setcounter{tocdepth}{3}
\tableofcontents
}
\section{1) Load \& Merge ACIC Track-1a}\label{load-merge-acic-track-1a}

\section{2) Recodes → Readable, Teaching-Friendly
Labels}\label{recodes-readable-teaching-friendly-labels}

\section{3) Conventional MAIHDA models (A → B →
C)}\label{conventional-maihda-models-a-b-c}

\begin{itemize}
\tightlist
\item
  \textbf{Model A (Additive + patient/practice RE):} captures main
  effects of components
\item
  \textbf{Model B (A + strata random intercept):} baseline
  intersectional heterogeneity
\item
  \textbf{Model C (B + W with random slope over strata):}
  treatment-effect heterogeneity
\end{itemize}

\section{4) Variance Partition (VPC) and Slope
Heterogeneity}\label{variance-partition-vpc-and-slope-heterogeneity}

\section{5) Visualise treatment-slope
heterogeneity}\label{visualise-treatment-slope-heterogeneity}

\pandocbounded{\includegraphics[keepaspectratio]{ACIC-Conventional-MAIHDA_files/figure-latex/slope-hist-1.pdf}}

\section{6) Results (auto-reported + one-paragraph
interpretation)}\label{results-auto-reported-one-paragraph-interpretation}

\begin{verbatim}
## **Auto-reported summary**  
## - Fixed effect of W (ATE proxy, Model C): 520.25 (SE 19.94, t = 26.09)  
## - Strata VPC (Model B): NA  
## - SD of W random slope across strata (Model C): NA  
## - Corr(Intercept, W) at strata (Model C): NA
\end{verbatim}

\textbf{Interpretation (reader-friendly):}\\
On average, exposure in treated post-periods (W = 1) is associated with
a change of about \textbf{520} units (SE 19.9).\\
Baseline differences between intersectional strata are \textbf{n/a} (VPC
≈ NA\%).\\
Treatment effects \textbf{vary across strata}: the random-slope SD is
about \textbf{NA}, suggesting many strata lie roughly between
\textbf{NA} and \textbf{NA} around the average effect.\\
The intercept--slope correlation (≈ NA) suggests \textbf{unclear}.

\begin{itemize}
\tightlist
\item
  Top 15 strata by size
\end{itemize}

\begin{table}

\caption{\label{tab:strata-top15}Top 15 intersectional strata by number of patient-year observations (with mean outcome and exposure rate).}
\centering
\begin{tabular}[t]{lrrrrl}
\toprule
Strata (readable) & n & patients & practices & Mean Y & W rate\\
\midrule
Sex: Female | Risk: Low (Q1) | Comorbidity: 2–3 | Deprivation: High | Plan: A & 37467 & 11320 & 495 & 1765.13 & 19.3\%\\
Sex: Male | Risk: Very High (Q4) | Comorbidity: 2–3 | Deprivation: Low | Plan: A & 30489 & 10660 & 500 & 474.28 & 17.9\%\\
Sex: Male | Risk: High (Q3) | Comorbidity: 2–3 | Deprivation: Low | Plan: A & 27087 & 9366 & 498 & 523.47 & 17.6\%\\
Sex: Female | Risk: Medium (Q2) | Comorbidity: 2–3 | Deprivation: High | Plan: A & 21973 & 6631 & 484 & 1668.33 & 19.3\%\\
Sex: Female | Risk: Low (Q1) | Comorbidity: 4–5 | Deprivation: High | Plan: A & 21967 & 6625 & 483 & 1715.59 & 19.9\%\\
\addlinespace
Sex: Female | Risk: Low (Q1) | Comorbidity: 2–3 | Deprivation: Mid | Plan: A & 20917 & 6723 & 494 & 1063.91 & 18.2\%\\
Sex: Male | Risk: Medium (Q2) | Comorbidity: 2–3 | Deprivation: Low | Plan: A & 20682 & 7194 & 494 & 563.28 & 17.9\%\\
Sex: Female | Risk: Medium (Q2) | Comorbidity: 2–3 | Deprivation: Mid | Plan: A & 20360 & 6482 & 490 & 1071.77 & 18.3\%\\
Sex: Male | Risk: Very High (Q4) | Comorbidity: 4–5 | Deprivation: Low | Plan: A & 18774 & 6508 & 494 & 476.17 & 17.2\%\\
Sex: Female | Risk: High (Q3) | Comorbidity: 2–3 | Deprivation: Mid | Plan: A & 18123 & 5778 & 495 & 1061.78 & 18.3\%\\
\addlinespace
Sex: Female | Risk: High (Q3) | Comorbidity: 2–3 | Deprivation: High | Plan: A & 17760 & 5396 & 490 & 1686.13 & 19.3\%\\
Sex: Female | Risk: Very High (Q4) | Comorbidity: 2–3 | Deprivation: Mid | Plan: A & 17156 & 5454 & 496 & 1066.38 & 18.6\%\\
Sex: Female | Risk: Very High (Q4) | Comorbidity: 2–3 | Deprivation: Low | Plan: A & 16987 & 5903 & 494 & 558.66 & 18.0\%\\
Sex: Male | Risk: High (Q3) | Comorbidity: 4–5 | Deprivation: Low | Plan: A & 16441 & 5741 & 494 & 502.37 & 17.6\%\\
Sex: Male | Risk: Medium (Q2) | Comorbidity: 2–3 | Deprivation: Mid | Plan: A & 16130 & 5068 & 488 & 1064.47 & 18.3\%\\
\bottomrule
\end{tabular}
\end{table}

\pandocbounded{\includegraphics[keepaspectratio]{ACIC-Conventional-MAIHDA_files/figure-latex/strata-top15-plot-1.pdf}}

\section{7) Notes}\label{notes}

\begin{itemize}
\tightlist
\item
  Strata are defined from \textbf{readable components}:
  \texttt{sex\ ×\ V1\_band\ ×\ V2\_band\ ×\ V4\_band\ ×\ plan} (dropping
  any single-level components in a given replicate).
\item
  \textbf{Model A} uses these components as \textbf{additive fixed
  effects}; \textbf{Model B} adds a \textbf{strata random intercept};
  \textbf{Model C} adds \texttt{W} and a \textbf{random slope of W by
  strata}.
\item
  We include \texttt{(1\textbar{}id.practice)} to respect
  \textbf{cluster randomisation} and \texttt{(1\textbar{}id.patient)}
  for repeated measures.
\item
  Convergence warnings can be informative; we already center \texttt{W}
  and try robust optimisers.
\end{itemize}

\end{document}
